apiVersion: v1
kind: Service
metadata:
  name: postfix
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  type: LoadBalancer
  selector:
    app: postfix
  ports:
  - name: smtp
    port: 25
    protocol: TCP
    targetPort: 25
  - name: smtps
    port: 465
    protocol: TCP
    targetPort: 465
  - name: submission
    port: 587
    protocol: TCP
    targetPort: 587
  loadBalancerIP: 192.168.100.50