apiVersion: v1
kind: Service
metadata:
  name: protonmail-bridge
spec:
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: protonmail-bridge
  ports:
  - name: smtp
    port: 25
    protocol: TCP
    targetPort: 25