apiVersion: v1
kind: Service
metadata:
  name: vikunja-service
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 3456
    protocol: TCP
    targetPort: http
  selector:
    app: vikunja
    release: vikunja
  type: ClusterIP