apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-files
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: clusterstorage-external
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi